# Generated by Django 4.2.1 on 2023-06-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_facility_reservation_roomtype_alter_customer_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
