# Generated by Django 4.2.1 on 2023-06-02 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_customer_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_type',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.usertype'),
        ),
    ]
