# Generated by Django 4.2.1 on 2023-06-03 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='room',
            name='reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='main.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='staff',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_as_staff', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
