# Generated by Django 4.2.1 on 2023-06-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_reservation_staff_remove_room_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='adult_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='child_count',
            field=models.IntegerField(default=0),
        ),
    ]
