# Generated by Django 4.2.1 on 2023-06-05 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='staff',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_as_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
