# Generated by Django 4.2.1 on 2023-06-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_room_images_image_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='room',
        ),
    ]
