# Generated by Django 4.2.1 on 2023-06-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_image_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_type',
        ),
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
