# Generated by Django 4.2.1 on 2023-06-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_customer_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='images',
            field=models.FileField(blank=True, upload_to='room_images'),
        ),
    ]
