# Generated by Django 4.2.1 on 2023-06-05 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_room_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='check_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_out_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
