# Generated by Django 4.2.1 on 2023-06-05 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_facility_faciliti_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='expected_arrival_date_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='expected_departure_date_time',
        ),
    ]
