# Generated by Django 4.2.1 on 2023-06-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_reservation_expected_arrival_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='conveniences',
            field=models.ManyToManyField(related_name='conveniences', to='main.faciliti'),
        ),
    ]
