# Generated by Django 4.2.1 on 2023-06-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_room_conveniences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.ManyToManyField(related_name='images', to='main.image'),
        ),
    ]
