# Generated by Django 4.2.1 on 2023-06-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_image_room_room_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
