# Generated by Django 4.2.1 on 2023-06-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_room_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancel',
            field=models.BooleanField(default=0),
        ),
    ]
