# Generated by Django 4.2.1 on 2023-06-06 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_reservation_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_as_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
